import { SurgicalItem, WHOItem, ScenarioDefinition, ScenarioType } from './types';

export const INITIAL_SURGICAL_ITEMS: SurgicalItem[] = [
  {
    id: 'lap-sponge-4x4',
    name: 'Lap Sponge 4x4 (Radiopaque)',
    category: 'sponges',
    baseline: 10,
    inCavity: 0,
    trayOut: 10,
    radiopaqueMarker: true,
    rfidTag: 'RFID-SPG-0941',
  },
  {
    id: 'suture-needle-3-0',
    name: '3-0 Vicryl Suture Needle',
    category: 'sharps',
    baseline: 5,
    inCavity: 0,
    trayOut: 5,
    radiopaqueMarker: true,
    rfidTag: 'RFID-SHP-8812',
  },
  {
    id: 'curved-mayo-forceps',
    name: 'Curved Mayo Scissors & Forceps',
    category: 'instruments',
    baseline: 4,
    inCavity: 0,
    trayOut: 4,
    radiopaqueMarker: true,
    rfidTag: 'RFID-INST-4421',
  },
  {
    id: 'suction-tip-yankauer',
    name: 'Yankauer Suction Tip',
    category: 'misc',
    baseline: 1,
    inCavity: 0,
    trayOut: 1,
    radiopaqueMarker: true,
    rfidTag: 'RFID-MSC-1102',
  },
];

export const INITIAL_WHO_CHECKLIST: WHOItem[] = [
  // Phase 1: SIGN IN (Before Induction)
  {
    id: 'who-signin-1',
    phase: 'SIGN_IN',
    label: 'Patient Identity & Consent Confirmed',
    description: 'Patient verbalized name, DOB, procedure, and consent verified against chart.',
    checked: true,
    requiredForClosure: false,
  },
  {
    id: 'who-signin-2',
    phase: 'SIGN_IN',
    label: 'Surgical Site Marked',
    description: 'Surgeon initials visible on operative quadrant (Left lower abdomen).',
    checked: true,
    requiredForClosure: false,
  },
  {
    id: 'who-signin-3',
    phase: 'SIGN_IN',
    label: 'Pulse Oximeter & Anesthesia Safety Check',
    description: 'Airway assessment complete; suction and emergency drugs checked.',
    checked: true,
    requiredForClosure: false,
  },

  // Phase 2: TIME OUT (Before Incision)
  {
    id: 'who-timeout-1',
    phase: 'TIME_OUT',
    label: 'Team Introduction & Roles',
    description: 'Lead Surgeon, Scrub Nurse, Circulator, and Anesthesiologist identified.',
    checked: true,
    requiredForClosure: false,
  },
  {
    id: 'who-timeout-2',
    phase: 'TIME_OUT',
    label: 'Antibiotic Prophylaxis Administered',
    description: 'IV Cefazolin 2g infused within 60 minutes prior to skin incision.',
    checked: true,
    requiredForClosure: false,
  },
  {
    id: 'who-timeout-3',
    phase: 'TIME_OUT',
    label: 'Sterility & Essential Imaging Displayed',
    description: 'Autoclave indicators verified sterile; pre-op CT scans on OR monitor.',
    checked: true,
    requiredForClosure: false,
  },

  // Phase 3: SIGN OUT (Before Closure) - REQUIRED FOR GATE CLEARANCE
  {
    id: 'who-signout-1',
    phase: 'SIGN_OUT',
    label: 'Procedure Recorded Accurately',
    description: 'Laparoscopic Sigmoid Colectomy recorded by circulating nurse.',
    checked: true,
    requiredForClosure: true,
  },
  {
    id: 'who-signout-2',
    phase: 'SIGN_OUT',
    label: 'Surgical Counts Reconciled & Verified Correct',
    description: 'Instrument, sponge, and needle counts verified by Scrub and Circulator.',
    checked: true,
    requiredForClosure: true,
  },
  {
    id: 'who-signout-3',
    phase: 'SIGN_OUT',
    label: 'Specimens Labeled with Patient Identifiers',
    description: 'Pathology container labeled with patient name, MRN, and anatomic site.',
    checked: true,
    requiredForClosure: true,
  },
  {
    id: 'who-signout-4',
    phase: 'SIGN_OUT',
    label: 'Equipment Issues & Recovery Concerns Reviewed',
    description: 'Post-op recovery plan, analgesia, and wound care discussed.',
    checked: true,
    requiredForClosure: true,
  },
];

export const PRESET_SCENARIOS: Record<ScenarioType, ScenarioDefinition> = {
  SCENARIO_A: {
    id: 'SCENARIO_A',
    title: 'Scenario A: Nominal 100% Match',
    badge: 'NOMINAL RECONCILIATION',
    description: 'All 10 Sponges, 5 Suture Needles, and 4 Forceps accounted for on sterile tray. Zero in cavity. All WHO sign-out gates signed.',
    expectedGate: 'GO',
    items: [
      {
        id: 'lap-sponge-4x4',
        name: 'Lap Sponge 4x4 (Radiopaque)',
        category: 'sponges',
        baseline: 10,
        inCavity: 0,
        trayOut: 10,
        radiopaqueMarker: true,
        rfidTag: 'RFID-SPG-0941',
      },
      {
        id: 'suture-needle-3-0',
        name: '3-0 Vicryl Suture Needle',
        category: 'sharps',
        baseline: 5,
        inCavity: 0,
        trayOut: 5,
        radiopaqueMarker: true,
        rfidTag: 'RFID-SHP-8812',
      },
      {
        id: 'curved-mayo-forceps',
        name: 'Curved Mayo Scissors & Forceps',
        category: 'instruments',
        baseline: 4,
        inCavity: 0,
        trayOut: 4,
        radiopaqueMarker: true,
        rfidTag: 'RFID-INST-4421',
      },
      {
        id: 'suction-tip-yankauer',
        name: 'Yankauer Suction Tip',
        category: 'misc',
        baseline: 1,
        inCavity: 0,
        trayOut: 1,
        radiopaqueMarker: true,
        rfidTag: 'RFID-MSC-1102',
      },
    ],
    whoCompleted: true,
    aiObservationSummary: 'Multimodal vision scan confirms 10 Lap Sponges, 5 Suture Needles, and 4 Forceps with high confidence (0.97). Radiopaque markers clearly detected.',
  },

  SCENARIO_B: {
    id: 'SCENARIO_B',
    title: 'Scenario B: Missing Lap Sponge #3',
    badge: 'CRITICAL RFO HAZARD',
    description: 'Tray count shows only 9 Lap Sponges (Baseline: 10). Delta = +1 missing item unaccounted for. Deterministic gate enforces HOLD.',
    expectedGate: 'HOLD',
    items: [
      {
        id: 'lap-sponge-4x4',
        name: 'Lap Sponge 4x4 (Radiopaque)',
        category: 'sponges',
        baseline: 10,
        inCavity: 0,
        trayOut: 9, // Missing 1!
        radiopaqueMarker: true,
        rfidTag: 'RFID-SPG-0941',
      },
      {
        id: 'suture-needle-3-0',
        name: '3-0 Vicryl Suture Needle',
        category: 'sharps',
        baseline: 5,
        inCavity: 0,
        trayOut: 5,
        radiopaqueMarker: true,
        rfidTag: 'RFID-SHP-8812',
      },
      {
        id: 'curved-mayo-forceps',
        name: 'Curved Mayo Scissors & Forceps',
        category: 'instruments',
        baseline: 4,
        inCavity: 0,
        trayOut: 4,
        radiopaqueMarker: true,
        rfidTag: 'RFID-INST-4421',
      },
      {
        id: 'suction-tip-yankauer',
        name: 'Yankauer Suction Tip',
        category: 'misc',
        baseline: 1,
        inCavity: 0,
        trayOut: 1,
        radiopaqueMarker: true,
        rfidTag: 'RFID-MSC-1102',
      },
    ],
    whoCompleted: true,
    aiObservationSummary: 'CRITICAL ALERT: Vision count detects only 9 Lap Sponges on the sterile Mayo tray. Lap Sponge #3 is missing from field. Delta = +1.',
  },

  SCENARIO_C: {
    id: 'SCENARIO_C',
    title: 'Scenario C: Needle Active in Cavity',
    badge: 'ACTIVE CAVITY ITEM',
    description: '1x 3-0 Vicryl Suture Needle remains logged inside patient peritoneal cavity. CavityIn = 1 forces DISCREPANCY [HOLD].',
    expectedGate: 'HOLD',
    items: [
      {
        id: 'lap-sponge-4x4',
        name: 'Lap Sponge 4x4 (Radiopaque)',
        category: 'sponges',
        baseline: 10,
        inCavity: 0,
        trayOut: 10,
        radiopaqueMarker: true,
        rfidTag: 'RFID-SPG-0941',
      },
      {
        id: 'suture-needle-3-0',
        name: '3-0 Vicryl Suture Needle',
        category: 'sharps',
        baseline: 5,
        inCavity: 1, // Retained in patient!
        trayOut: 4,
        radiopaqueMarker: true,
        rfidTag: 'RFID-SHP-8812',
      },
      {
        id: 'curved-mayo-forceps',
        name: 'Curved Mayo Scissors & Forceps',
        category: 'instruments',
        baseline: 4,
        inCavity: 0,
        trayOut: 4,
        radiopaqueMarker: true,
        rfidTag: 'RFID-INST-4421',
      },
      {
        id: 'suction-tip-yankauer',
        name: 'Yankauer Suction Tip',
        category: 'misc',
        baseline: 1,
        inCavity: 0,
        trayOut: 1,
        radiopaqueMarker: true,
        rfidTag: 'RFID-MSC-1102',
      },
    ],
    whoCompleted: true,
    aiObservationSummary: 'SAFETY INTERVENTION: Suture Needle #5 is registered in patient cavity. Laparoscopic extraction or needle magnetic sweep required.',
  },

  SCENARIO_D: {
    id: 'SCENARIO_D',
    title: 'Scenario D: Dynamic Sterile Pack Addition',
    badge: 'MID-OP STERILE PACK',
    description: 'Surgeon requests an additional sterile pack of 5 Lap Sponges mid-case. Baseline dynamically increments from 10 to 15 with SHA-256 block commit.',
    expectedGate: 'GO',
    items: [
      {
        id: 'lap-sponge-4x4',
        name: 'Lap Sponge 4x4 (Radiopaque)',
        category: 'sponges',
        baseline: 15, // Incremented by +5
        inCavity: 0,
        trayOut: 15,
        radiopaqueMarker: true,
        rfidTag: 'RFID-SPG-0941',
      },
      {
        id: 'suture-needle-3-0',
        name: '3-0 Vicryl Suture Needle',
        category: 'sharps',
        baseline: 5,
        inCavity: 0,
        trayOut: 5,
        radiopaqueMarker: true,
        rfidTag: 'RFID-SHP-8812',
      },
      {
        id: 'curved-mayo-forceps',
        name: 'Curved Mayo Scissors & Forceps',
        category: 'instruments',
        baseline: 4,
        inCavity: 0,
        trayOut: 4,
        radiopaqueMarker: true,
        rfidTag: 'RFID-INST-4421',
      },
      {
        id: 'suction-tip-yankauer',
        name: 'Yankauer Suction Tip',
        category: 'misc',
        baseline: 1,
        inCavity: 0,
        trayOut: 1,
        radiopaqueMarker: true,
        rfidTag: 'RFID-MSC-1102',
      },
    ],
    whoCompleted: true,
    aiObservationSummary: 'Sterile Pack Refill verified: 5 new Lap Sponges registered. New baseline total: 15. All 15 sponges visually confirmed on expanded Mayo tray.',
  },
};
